config/routes.rb
Survey::Application.routes.draw do
  resources :questions

  root :to => 'home#index'
  match 'complete' => 'home#complete'
  match 'random' => 'home#random'

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :answer, :ip, :question, :set, :set_id, :starttime
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
  def mobile_device?
    if session[:mobile_param]
      session[:mobile_param] == "1"
    else
      request.user_agent =~ /Mobile|webOS/
    end
  end
  helper_method :mobile_device?
  
  def handle_unverified_request
    # Would like to avoid reseting the session, WARNING this isnt a secure application
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :set_variables, :only => [:random]
  before_filter :set_defaultquestions, :only => [:random]

  private
  def set_variables
    @setspath = "app/assets/images/sets/"
    @sets = Dir.glob(@setspath + "*").map { |f| f.split('/').last }
  end

  def set_defaultquestions
    @default_questions =  [ {
      :q => "First question, yes or no?",
      :a => ["Yes", "No"],
      :s => "alert(grabText(this))",
      }, {
      :q => "Second question, check it:",
      :a => ["Yes", "No", "Maybe"],
      :t => CHECKBOX,
      }, {
      :q => "Third question, tell me more:",
      :a => [""],
      :t => TEXTBOX,
      } ]
  end

  public
  def index
    session[:starttime] = Time.now
  end

  def random
    if not params[:complete] or params[:complete].length < @sets.length
      @set = @sets.sample
      if params[:complete]
        while params[:complete].include?(@set.to_s)
          @set = @sets.sample
        end
      end
      @images = Dir.glob(@setspath + @set.to_s + "/*.jpg").sort
      @description = File.read(@setspath + @set.to_s + "/description.html")
      respond_to do |format|
        format.html # next.html.erb
      end
    else
      redirect_to :action => :complete
    end
  end

  def complete
    reset_session
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(params[:question])
    @question.ip = request.remote_ip
    @question.starttime = session[:starttime]

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/_nextform.html.erb
<form action="/random" method="post" id="next" style="display:none">
	<% if params[:complete] %>
	<% params[:complete].each do |a| %>
	<input type="hidden" name="complete[]" value="<%= a %>">
	<% end %>
	<% end %>
	<input type="hidden" name="complete[]" value="<%= set %>">
</form>

<script type="text/javascript">
	function onComplete() {
		$("#next").submit();
	}
</script>

app/views/home/complete.html.erb
<% content_for :title do %>
<%= Settings.name %> Survey Completed
<% end %>
<% content_for :header do %>
<%= Settings.name %> Survey - Completed<br />
Thank you
<% end %>
<% content_for :footer do %>
<% end %>

app/views/home/index.html.erb
<%
 @questions = [ {
# This demonstrates a regular question, with a javascript action
# which has been predefined to skip upon an answer
:q => "Sample question, would you like to skip over the next?",
:a => ["Yes", "No"],
:s => SKIP_CONDITIONAL + "(this,'Yes',2,1)",
} , {
# This demonstrates the other field
:q => "Not skipping, how is your day?",
:a => ["Good", "Bad", "Ugly", OTHER],
} , {
# This demonstates the checkboxes as well as the other field
:q => "How is your day?",
:a => ["Good", "Bad", "Ugly", OTHER],
:t => CHECKBOX,
} , {
# This demonstates multiple text boxes and their labels
:q => "What is new?",
:a => ["First:", "Second:"],
:t => TEXTBOX,
} , {
# This demonstrates a large text box
:q => "Can you describe more?",
:a => [""],
:t => TEXTBOX,
} ]
%>
<% content_for :title do %>
<%= Settings.name %> Survey
<% end %>
<% content_for :header do %>
<%= Settings.name %> Survey - Index
<% end %>
<% content_for :footer do %>
<%= render "layouts/default_footer" %>
<% end %>
<% if mobile_device? %>
<div>Disclaimer: Mobile is still in development. You may have to scroll around if you dont see a question. </div>
<% end %>
<div class="set" id="intro">
		<%= render :partial => "questions/qalist", :locals => { :questions => @questions } %>
</div>

<script type="text/javascript">
/* Upon success, the function onComplete is called
 * You should overwrite it to do whatever you need such
 * as take you to the next page
 */
	function onComplete() {
		window.location = "/random";
	}
</script>

app/views/home/random.html.erb
<% content_for :title do %>
<%= Settings.name %> Survey - <%= @set %>
<% end %>
<% content_for :header do %>
<%= Settings.name %> Survey - <%= @set%>
<% end %>
<% content_for :footer do %>
<%= render "layouts/default_footer" %>
<% end %>

<%= 
render :partial => "questions/default_set_images", :locals => {
:set => @set.html_safe.gsub(" ", "_"),
:questions => @default_questions,
:images => @images,
:description => @description
}
%>
<%= render :partial => "nextform", :locals => {:set => @set } %>

app/views/layouts/_default_footer.html.erb
&copy; <%= Settings.copyright %>

app/views/layouts/_default_header.html.erb
<%= Settings.name %> survey

app/views/layouts/_slideshow.html.erb
<div class="images">
	<div class="slider-wrapper theme-light">
		<div id="slider" class="nivoSlider">
			<% images.each do |image| %>
			<%= image_tag "#{image.split('images/').last}" %>
			<% end %>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= yield :title %></title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tag %>
	</head>
	<body>
		<div class="container">
			<div class="headerdiv">
				<%= yield :header %>
			</div>
			<div class="bodydiv">
				<%= yield %>
			</div>
			<div class="footerdiv">
				<%= yield :footer %>
			</div>
		</div>
	</body>
</html>

app/views/questions/_default_set.html.erb
<div class="set" id="<%= set %>">
	<div class="wrapper pad">
		<div class="description">
			<%= raw(description.html_safe) %>
		</div>
	</div>
	<%= render :partial => "questions/qalist", :locals => { :questions => questions } %>
</div>

app/views/questions/_default_set_images.html.erb
<div class="set" id="<%= set %>">
	<div class="wrapper pad">
		<%= render :partial => "layouts/slideshow", :locals => { :images => images } %>
		<div class="description">
			<%= raw(description.html_safe) %>
		</div>
	</div>
	<%= render :partial => "questions/qalist", :locals => { :questions => questions } %>
</div>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br />
    <%= f.text_field :question %>
  </div>
  <div class="field">
    <%= f.label :answer %><br />
    <%= f.text_field :answer %>
  </div>
  <div class="field">
    <%= f.label :set %><br />
    <%= f.number_field :set %>
  </div>
  <div class="field">
    <%= f.label :set_id %><br />
    <%= f.number_field :set_id %>
  </div>
  <div class="field">
    <%= f.label :ip %><br />
    <%= f.text_field :ip %>
  </div>
  <div class="field">
    <%= f.label :starttime %><br />
    <%= f.datetime_select :starttime %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/_qalist.html.erb
<div class="qalist">
<% questions.each_with_index do |q, idx| %>
<%= render :partial => "questions/question", :locals => { :id => idx, :question => q[:q], :answer => q[:a], :func => q[:s], :type => q[:t] } %>
<% end %>
</div>

app/views/questions/_question.html.erb
<div id='question<%= id %>' class="qa">
	<div class='question'><%= question %></div>
	<div class='answer'>
		<div class="outer-center">
			<div class="inner-center">
				<table border=0>
					<% case type
					when CHECKBOX %>
					<% answer.each_with_index do |ans,idx| %>
					<tr>
						<td>
						<input type="checkbox" value="<%= ans %>" id="<%= "q_#{id}_#{idx}" %>" <%= if ans == OTHER then "onchange='" + REPLACE_OTHER + "(this)'" end %>/>
						</td>
						<td align="left"><label for="<%= "q_#{id}_#{idx}" %>"><%= ans %></label></td>
					</tr>
					<% end %>
					<tr>
						<td colspan="2" align="center" <%= if mobile_device? then "style='padding-top:2em'" end %>>
						<input type="button" class="white button" onclick="<%= if defined?(func) and func then func + ";" end %><%= CHECKBOX %>(this)" value="Submit" />
						</td>
					</tr>
					<% when TEXTBOX %>
					<% answer.each_with_index do |ans,idx| %>
					<tr>
						<% if ans %>
						<td><%= ans %></td>
						<% end %>
						<td>						<textarea class="textbox" <%= (ans == "") ? "rows='3' cols='50'" : "" %>></textarea></td>
					</tr>
					<% end %>
					<tr>
						<td colspan="2" align="center" <%= if mobile_device? then "style='padding-top:2em'" end %>>
						<input type="button" class="white button" onclick="<%= if defined?(func) and func then func + ";" end %><%= TEXTBOX %>(this)" value="Submit" />
						</td>
					</tr>
					<% else %>
					<tr>
						<td> <% answer.each do |ans| %>
						<input type="button" class="white button" value="<%= ans %>" onclick="<%= if defined?(func) and func then func + ";" end %><%= BUTTON %>(this)" />
						<% end %> </td>
					</tr>
					<% end %>
				</table>
			</div>
		</div>
		<div class="clear"></div>
	</div>
</div>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <tr>
    <th>Question</th>
    <th>Answer</th>
    <th>Set</th>
    <th>Set Id</th>
    <th>Ip</th>
    <th>Start Time</th>
    <th>Created</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @questions.each do |question| %>
  <tr>
    <td><%= question.question %></td>
    <td><%= question.answer %></td>
    <td><%= question.set %></td>
    <td><%= question.set_id %></td>
    <td><%= question.ip %></td>
    <td><%= question.starttime %></td>
    <td><%= question.created_at %></td>
    <td><%= link_to 'Show', question %></td>
    <td><%= link_to 'Edit', edit_question_path(question) %></td>
    <td><%= link_to 'Destroy', question, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Question:</b>
  <%= @question.question %>
</p>

<p>
  <b>Answer:</b>
  <%= @question.answer %>
</p>

<p>
  <b>Set:</b>
  <%= @question.set %>
</p>

<p>
  <b>Set:</b>
  <%= @question.set_id %>
</p>

<p>
  <b>Ip:</b>
  <%= @question.ip %>
</p>

<p>
  <b>Starttime:</b>
  <%= @question.starttime %>
</p>


<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>